language: ruby
rvm:
- '2.1'
install: gem install jekyll
script: "./travis_build.sh"
notifications:
  hipchat:
    rooms:
      secure: mWlSpRdoI3WoX9RY00uNGpJonoxd3gSMcbBXMAtA0YegdCI7TMrtSzKWuWCCNY4K4U5J6r4trHtRvjOeGGbCHFSnaqzs6rg1ocfs2zxqHHXuVxthrM2njFT8KaSkaNVz+V/Vg6+iDe8pIO3hf83xr+i0exRvujkSfTKsFDx7d/M=
env:
  global:
    secure: cT2t/qoSELBzkia2whVSWYwiMMqDAi3sDJM/apRMbz6sLh2N2T5xaOILo5nRUbUgv57vCytqwXj9ozetsCl2pWMwNtpAzDISatB5xCCfZFdCYgjrE5a+7F0o8zrvB1Mfi/kxYJysK0IWOST5sjK4cSjts6ArohLB5ZVrQjAtZGw=
