language: ruby
rvm:
- '2.1'
install: gem install jekyll
script: "./travis_build.sh"
notifications:
  hipchat:
    rooms:
      secure: mWlSpRdoI3WoX9RY00uNGpJonoxd3gSMcbBXMAtA0YegdCI7TMrtSzKWuWCCNY4K4U5J6r4trHtRvjOeGGbCHFSnaqzs6rg1ocfs2zxqHHXuVxthrM2njFT8KaSkaNVz+V/Vg6+iDe8pIO3hf83xr+i0exRvujkSfTKsFDx7d/M=
env:
  global:
    secure: E+5JpojBx7aedhTFoEafb68gkJd1l5fxCcCtMAlEY9vBSi2yzHOh83FGK65XSGS0BzmnDc7FiIEzuT8NNGnFFurTpj/IbrdwZtieECpON2wVzIHsz/TPT2Boga/yeIujbl0iVsHdU02+jFSHLaeNmmkZ/zsTkC4K+NEH1l+wjWA=
