name: RMIT Vietnam IT Club
markdown: redcarpet
pygments: true
encoding: UTF-8
exclude: [README.mkd, scripts]

authors:

  nhanb:
    name: Bùi Thành Nhân
    display_name: Bùi Thành Nhân
    gravatar: d222558bce9f0f82c132f5903c3b9cfe
    email: nhan.buithanh@rmitc.org
    web: http://nerdyweekly.com
    twitter: nhanbt
    github: nhanb

  truongtx:
    name: Trần Xuân Trường
    display_name: TruongTx
    gravatar: 0392d0b2bfc76ef5f7e26f637f7501bc
    email: me@truongtx.me
    web: http://truongtx.me
    twitter: mr_truong_tx
    github: tmtxt
    facebook: mr.truong.tx

  hadobac:
    name: Đỗ Bắc Hà
    display_name: Đỗ Bắc Hà
    email: hadobac333@gmail.com
    facebook: hahnpremium

  linh:
    name: Nguyễn Vĩnh Linh
    display_name: Nguyễn Vĩnh Linh

  tklarryonline:
    name: Nguyễn Thanh Luân
    display_name: TKLarry
    gravatar: 49b0f1c76ab8838c3314a06bebf05f2f
    email: luan@tklarryonline.me
    web: http://tklarryonline.me
    github: tklarryonline
    twitter: tklarryonline

  phunehehe:
    name: Hoàng Xuân Phú
    display_name: Hoàng Xuân Phú
    github: phunehehe

  anhnguyen:
    name: Nguyễn Tuấn Anh
    display_name: Nguyễn Tuấn Anh

  khangnguyen:
    name: Nguyễn Nam Khang
    display_name: Nguyễn Nam Khang

  tommyly:
    name: Tommy Ly
    display_name: Tommy Ly

  huanle:
    name: Huan Le
    display_name: Huan Le

  duynguyen:
    name: Duy Nguyễn
    display_name: Duy Nguyễn

  locvu:
    name: Vũ Xuân Lộc
    display_name: Vũ Xuân Lộc

  minhdao:
    name: Đào Tiến Minh
    display_name: Đào Tiến Minh

